<h3>Please login :</h3>
<form method="post" action=".">
	<input type="hidden" name="action" value="login"/>
	<p>
		<label for="email">Email</label> : <input type="text" name="email" id="email"/>
		<br />
		<label for="password">Password</label> : <input type="password" name="password" id="password"/>
	</p>
	<p>
		<input type="submit" /> <input type="reset" />
	</p>
</form>

<p>Don't have an account? Register <a href="?action=register">here</a>.</p>
